// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace Model.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220922103945_Edit")]
    partial class Edit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Model.Endings", b =>
                {
                    b.Property<int>("EndingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("endings_id");

                    b.Property<string>("Ending")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ending");

                    b.Property<int>("EndingsTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endings_type_id");

                    b.Property<bool>("IsFemaleEnding")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_female_ending");

                    b.HasKey("EndingsId")
                        .HasName("pk_endings");

                    b.HasIndex("EndingsTypeId");

                    b.ToTable("endings");

                    b.HasCheckConstraint("ch_is_female_ending", "is_female_ending IN (0, 1)");

                    b.HasData(
                        new
                        {
                            EndingsId = 1,
                            Ending = "а",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 2,
                            Ending = "е",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 3,
                            Ending = "и",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 4,
                            Ending = "о",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 5,
                            Ending = "у",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 6,
                            Ending = "э",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 7,
                            Ending = "ю",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 8,
                            Ending = "я",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 9,
                            Ending = "ая",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 10,
                            Ending = "ея",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 11,
                            Ending = "ия",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 12,
                            Ending = "оя",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 13,
                            Ending = "уя",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 14,
                            Ending = "эя",
                            EndingsTypeId = 1,
                            IsFemaleEnding = true
                        },
                        new
                        {
                            EndingsId = 15,
                            Ending = "б",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 16,
                            Ending = "в",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 17,
                            Ending = "г",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 18,
                            Ending = "д",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 19,
                            Ending = "ж",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 20,
                            Ending = "й",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 21,
                            Ending = "к",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 22,
                            Ending = "л",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 23,
                            Ending = "м",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 24,
                            Ending = "н",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 25,
                            Ending = "п",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 26,
                            Ending = "р",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 27,
                            Ending = "с",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 28,
                            Ending = "т",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 29,
                            Ending = "ф",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        },
                        new
                        {
                            EndingsId = 30,
                            Ending = "х",
                            EndingsTypeId = 1,
                            IsFemaleEnding = false
                        });
                });

            modelBuilder.Entity("Model.EndingsType", b =>
                {
                    b.Property<int>("EndingsTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("endings_type_id");

                    b.Property<string>("EndingsTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("endings_type_name");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("language_id");

                    b.HasKey("EndingsTypeId")
                        .HasName("pk_endings_type");

                    b.HasIndex("LanguageId");

                    b.ToTable("endings_type");

                    b.HasData(
                        new
                        {
                            EndingsTypeId = 1,
                            EndingsTypeName = "Standard",
                            LanguageId = 1
                        });
                });

            modelBuilder.Entity("Model.FrequencyType", b =>
                {
                    b.Property<int>("FrequencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("frequency_type_id");

                    b.Property<string>("FrequencyTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency_type_name");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("language_id");

                    b.HasKey("FrequencyTypeId")
                        .HasName("pk_frequency_type");

                    b.HasIndex("FrequencyTypeName")
                        .IsUnique();

                    b.HasIndex("LanguageId");

                    b.ToTable("frequency_type");

                    b.HasData(
                        new
                        {
                            FrequencyTypeId = 1,
                            FrequencyTypeName = "Standard",
                            LanguageId = 1
                        });
                });

            modelBuilder.Entity("Model.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("language_id");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language_name");

                    b.HasKey("LanguageId")
                        .HasName("pk_language");

                    b.HasIndex("LanguageName")
                        .IsUnique();

                    b.ToTable("language");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            LanguageName = "Russian"
                        });
                });

            modelBuilder.Entity("Model.Letter", b =>
                {
                    b.Property<int>("LetterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("letter_id");

                    b.Property<char>("Char")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("char");

                    b.Property<bool>("IsVowel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_vowel");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("language_id");

                    b.HasKey("LetterId")
                        .HasName("pk_letter");

                    b.HasIndex("Char")
                        .IsUnique();

                    b.HasIndex("LanguageId");

                    b.ToTable("letter");

                    b.HasCheckConstraint("ch_is_vowel", "is_vowel IN (0, 1)");

                    b.HasData(
                        new
                        {
                            LetterId = 1,
                            Char = 'а',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 2,
                            Char = 'б',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 3,
                            Char = 'в',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 4,
                            Char = 'г',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 5,
                            Char = 'д',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 6,
                            Char = 'е',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 7,
                            Char = 'ё',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 8,
                            Char = 'ж',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 9,
                            Char = 'з',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 10,
                            Char = 'и',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 11,
                            Char = 'й',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 12,
                            Char = 'к',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 13,
                            Char = 'л',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 14,
                            Char = 'м',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 15,
                            Char = 'н',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 16,
                            Char = 'о',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 17,
                            Char = 'п',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 18,
                            Char = 'р',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 19,
                            Char = 'с',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 20,
                            Char = 'т',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 21,
                            Char = 'у',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 22,
                            Char = 'ф',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 23,
                            Char = 'х',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 24,
                            Char = 'ц',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 25,
                            Char = 'ч',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 26,
                            Char = 'ш',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 27,
                            Char = 'щ',
                            IsVowel = false,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 28,
                            Char = 'ы',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 29,
                            Char = 'э',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 30,
                            Char = 'ю',
                            IsVowel = true,
                            LanguageId = 1
                        },
                        new
                        {
                            LetterId = 31,
                            Char = 'я',
                            IsVowel = true,
                            LanguageId = 1
                        });
                });

            modelBuilder.Entity("Model.LetterFrequency", b =>
                {
                    b.Property<int>("FrequencyTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frequency_type_id");

                    b.Property<int>("LetterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("letter_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frequency");

                    b.HasKey("FrequencyTypeId", "LetterId");

                    b.HasIndex("LetterId");

                    b.ToTable("letter_frequency");

                    b.HasCheckConstraint("ch_frequency", "frequency >= 0");

                    b.HasData(
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 1,
                            Frequency = 801
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 2,
                            Frequency = 159
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 3,
                            Frequency = 454
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 4,
                            Frequency = 170
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 5,
                            Frequency = 298
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 6,
                            Frequency = 845
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 7,
                            Frequency = 4
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 8,
                            Frequency = 94
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 9,
                            Frequency = 165
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 10,
                            Frequency = 735
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 11,
                            Frequency = 121
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 12,
                            Frequency = 349
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 13,
                            Frequency = 440
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 14,
                            Frequency = 321
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 15,
                            Frequency = 670
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 16,
                            Frequency = 1097
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 17,
                            Frequency = 281
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 18,
                            Frequency = 473
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 19,
                            Frequency = 547
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 20,
                            Frequency = 626
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 21,
                            Frequency = 262
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 22,
                            Frequency = 26
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 23,
                            Frequency = 97
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 24,
                            Frequency = 38
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 25,
                            Frequency = 34
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 26,
                            Frequency = 23
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 27,
                            Frequency = 26
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 28,
                            Frequency = 190
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 29,
                            Frequency = 32
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 30,
                            Frequency = 64
                        },
                        new
                        {
                            FrequencyTypeId = 1,
                            LetterId = 31,
                            Frequency = 201
                        });
                });

            modelBuilder.Entity("Model.Endings", b =>
                {
                    b.HasOne("Model.EndingsType", "EndingsType")
                        .WithMany()
                        .HasForeignKey("EndingsTypeId")
                        .HasConstraintName("fk_endings_type_endings")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndingsType");
                });

            modelBuilder.Entity("Model.EndingsType", b =>
                {
                    b.HasOne("Model.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("fk_language_endings_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Model.FrequencyType", b =>
                {
                    b.HasOne("Model.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("fk_language_frequency_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Model.Letter", b =>
                {
                    b.HasOne("Model.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("fk_language_letter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Model.LetterFrequency", b =>
                {
                    b.HasOne("Model.FrequencyType", "FrequencyType")
                        .WithMany()
                        .HasForeignKey("FrequencyTypeId")
                        .HasConstraintName("fk_frequency_type_letter_frequency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Letter", "Letter")
                        .WithMany()
                        .HasForeignKey("LetterId")
                        .HasConstraintName("fk_letter_letter_frequency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrequencyType");

                    b.Navigation("Letter");
                });
#pragma warning restore 612, 618
        }
    }
}
